[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[nodejs]
disabled = true

[git_branch]
format = "[<$branch>]($style) "
symbol = "ğŸŒ± "

[git_status]
style="red"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "âŒ "
ahead = "ğŸ‘†$count"
behind = "ğŸ‘‡$count"
diverged = "ğŸ‘†${ahead_count}ğŸ‘‡${behind_count}"
untracked = "??x$count "
stashed = ""
modified = "[Mx$count](yellow) "
staged = '[Ax$count](green) '
renamed = "Â»"
deleted = "Dx$count "