[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[nodejs]
disabled = true

[git_branch]
format = "[$branch]($style) "
symbol = "ğŸŒ± "

[git_status]
style="red"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "âŒ "
ahead = "ğŸ‘†[$count](green)"
behind = "ğŸ‘‡$count"
diverged = "ğŸ‘†[${ahead_count}](green)ğŸ‘‡${behind_count}"
untracked = "??*$count "
stashed = ""
modified = "[M*$count](yellow) "
staged = '[A*$count](green) '
renamed = "Â»"
deleted = "D*$count "