[package]
disabled = true

[battery]
full_symbol = 'ğŸ”‹'
charging_symbol = 'ğŸ”Œ'
discharging_symbol = 'âš¡'

[[battery.display]]
threshold = 100
style = 'yellow'

[directory]
fish_style_pwd_dir_length = 1
repo_root_style = 'yellow bold'

[nodejs]
disabled = false
format = "[â¬¢ $version](bold green) "

[git_branch]
format = "[$branch]($style) "
symbol = "ğŸŒ± "

[git_status]
style="red"
format = '([$ahead_behind$all_status]($style) )'
conflicted = "âŒ "
ahead = "ğŸ‘†[${count}](green) "
behind = "ğŸ‘‡$count "
diverged = "ğŸ‘†[${ahead_count}](green)ğŸ‘‡${behind_count} "
untracked = "[?$count](purple) "
stashed = ""
modified = "[*$count](yellow) "
staged = '[+$count](green) '
renamed = "Â»"
deleted = "-$count "

[time]
disabled = true
format = '[\[$time\]](green) '
time_format = "%m-%d %T"
