#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
lefthook = "latest"
node = "latest"
pnpm = "latest"
shfmt = "latest"
starship = "latest"
"github:d-kuro/gwq" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:difit" = "latest"
rust = "latest"
helix = "latest"
yazi = "latest"
"github:trasta298/keifu" = "latest"
"github:laishulu/macism" = { version = "latest", os = ["macos"] }
"github:jfernandez/mdserve" = { version = "latest", bin = "mdserve" }
"npm:@openai/codex" = "latest"
colima = "latest"
docker-cli = "latest"
lima = "latest"

[settings]
trusted_config_paths = [
  '~/ghq/github.com/miyaoka/',
  '~/ghq/github.com/studio-design/',
  '~/worktrees/github.com/miyaoka',
  '~/worktrees/github.com/studio-design/',
]
idiomatic_version_file_enable_tools = []
