[tools]
bun = "latest"
deno = "latest"
fzf = "latest"
gh = "latest"
node = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
pnpm = "latest"

[settings]
trusted_config_paths = [ 
  '~/src/github.com/miyaoka/',
  '~/src/github.com/studio-design/'
 ]
idiomatic_version_file_enable_tools = []
