#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "latest"
deno = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
lefthook = "latest"
node = "latest"
pnpm = "latest"
shfmt = "latest"
starship = "latest"
"github:d-kuro/gwq" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:difit" = "latest"

[settings]
trusted_config_paths = [ 
  '~/src/github.com/miyaoka/',
  '~/src/github.com/studio-design/'
 ]
idiomatic_version_file_enable_tools = []
