[package]
disabled = true

[gcloud]
disabled = true

[battery]
full_symbol = 'ğŸ”‹'
charging_symbol = 'ğŸ”Œ'
discharging_symbol = 'âš¡'

[[battery.display]]
threshold = 100
style = 'yellow'

[directory]
fish_style_pwd_dir_length = 1
repo_root_style = 'yellow bold'
truncate_to_repo = false
truncation_length = 2

[nodejs]
disabled = false
format = "[â¬¢ $version](bold green) "

[bun]
style="purple"

[git_branch]
format = "[$branch]($style)${custom.github_pr} "
symbol = "ğŸŒ± "

[git_status]
style="red"
format = '([$ahead_behind$all_status]($style) )'
conflicted = "âŒ "
ahead = "ğŸ‘†[${count}](green) "
behind = "ğŸ‘‡$count "
diverged = "ğŸ‘†[${ahead_count}](green)ğŸ‘‡${behind_count} "
untracked = "[?$count](purple) "
stashed = ""
modified = "[*$count](yellow) "
staged = '[+$count](green) '
renamed = "Â»"
deleted = "-$count "

[time]
disabled = false
format = '[\[$time\]](green) '
time_format = "%R"

# GitHub PRç•ªå·ã¨ã‚¿ã‚¤ãƒˆãƒ«ã‚’è¡¨ç¤ºã™ã‚‹ã‚«ã‚¹ã‚¿ãƒ ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«
[custom.github_pr]
description = "Display GitHub PR number and title with cache"
command = "bunx github:miyaoka/github-pr-info"
when = "git rev-parse --git-dir"
format = "[$output]($style) "
style = "blue"
ignore_timeout = true
